---
- name: PostgreSQL Libraries for geerlingguy.postgresql
  hosts: localhost
  tasks:
    - package:
        name: python2-psycopg2.x86_64
        state: present
      become: yes

- name: Install PostgreSQL Community Edition
  hosts: pq
  become: yes
  roles:
    - pgsqlrepo
    - geerlingguy.postgresql
    - pgcommon
    - pgextension
    - pgBackRest
    - pgstandby
