---
- name: PostgreSQL Libraries for geerlingguy.postgresql
  hosts: localhost
  tasks:
    - package:
        name: python-psycopg2
        state: present
      become: yes
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Install PostgreSQL Community Edition
  hosts: "{{ hostgroup | default('unknownhost') }}"
  become: yes
  roles:
    - pgsqlrepo
    - geerlingguy.postgresql
    - pgcommon
    - pgextension