pgbackreststanza: "db1"
pgbackrestrepo: "/net/192.168.56.91/var/lib/pgbackrest"

pgbackrest_recovery_option:
  - "standby_mode=on"
  - "primary_conninfo=host={{dbprimaryhost}} user=repuser"
  - "recovery_target_timeline=latest"
  - "archive_cleanup_command=pg_archivecleanup -d {{postgresql_data_dir}} %r"
