- name: Install pgbackrest
  package:
    name: "pgbackrest"
    state: present

- name: Template pgbackrest.conf
  template:
    src: pgbackrest.conf.j2
    dest: /etc/pgbackrest.conf
    owner: root
    group: root

- name: pgbackrest Logfile directory
  file:
    path: /var/log/pgbackrest
    state: directory
    owner: postgres
    group: postgres
    mode: 0750

- name: pgbackrest stanze directory
  file:
    path: "{{pgbackrestrepo}}"
    state: directory
    owner: postgres
    group: postgres
    mode: 0750

- name: pgbackrest stanza-create
  command: pgbackrest --stanza={{pgbackreststanza}} --log-level-console=info stanza-create
  args:
    creates: "{{pgbackrestrepo}}/archive"
  register: cmdout
  become_user: postgres

- debug: msg="{{ cmdout.stdout_lines }}"
  when: cmdout is defined

- name: pgbackrest check
  command: pgbackrest --stanza={{pgbackreststanza}} --log-level-console=info check
  register: cmdout
  become_user: postgres

- debug: msg="{{ cmdout.stdout_lines }}"
  when: cmdout is defined

