- name: Install Extensions
  postgresql_ext:
    name: "{{item.name}}"
    db: "{{item.db}}"
  become_user: "{{postgresql_user}}"
  with_items:
    - "{{postgresql_extensions}}"
  when: dbcluster_role == 'primary' and postgresql_extensions is defined
